load initial-states-smc

mod CASSANDRA-ANALYSIS is
  inc CASSANDRA .
  inc APMAUDE .
  inc SAMPLER .
  inc INITIAL-STATES .

  eq LIMIT = 1.0e+1000000 .

  eq replicaFactor = 3 .

  op initConfig : -> Config .
  eq initConfig = run(initState,LIMIT) .

  eq initState = init(nbOfRoTxns,nbOfWoTxns,nbOfRwTxns,
      nbOfCls,nbOfServs,nbOfKeys,nbOfRepls,
      nbOfOpsPerRoTxn,nbOfOpsPerWoTxn,nbOfOpsPerRwTxn,kad) . 

  --- Init parameters 
  eq nbOfRoTxns = 1 .  
  eq nbOfWoTxns = 0 .  
  eq nbOfRwTxns = 0 .
  eq nbOfOpsPerRoTxn = 1 .
  eq nbOfOpsPerWoTxn = 0 .
  eq nbOfOpsPerRwTxn = 0 .  --- must be even number
  eq nbOfCls = 4 .
  eq nbOfServs  = 2 .  
  eq nbOfKeys = 2 .  
  eq nbOfRepls = replicaFactor .
  eq kad = zipf .
  eq delay = sampleLogNormal(3.0,2.0) .


---(
    eq initState =
       { 0.0 | nil }
       { 0.0, start to 1} { 0.0, start to 2}
       < 1001 : Monitor | log: empty >


       < 1 : Client | coord: 10, 
                      requestQueue: (< 100 : Txn | operations: read(1),
                                                  readSet: empty, writeSet: empty,
                                                  version: eptVersion, consLv: quorum > ;;
                                    < 101 : Txn | operations: read(1),
                                                  readSet: empty, writeSet: empty,
                                                  version: eptVersion, consLv: quorum >),
                      waitingList: emptyTxnList, lockedKeys: empty,
                      executing: null, committed: null >

       < 2 : Client | coord: 20, 
                      requestQueue: (< 200 : Txn | operations: write(1,"b"),
                                                  readSet: empty, writeSet: empty,
                                                  version: eptVersion, consLv: quorum > ;;
                                     < 201 : Txn | operations: write(1,"c"),
                                                  readSet: empty, writeSet: empty,
                                                  version: eptVersion, consLv: quorum >),
                      waitingList: emptyTxnList, lockedKeys: empty,
                      executing: null, committed: null >
---(
       < 3 : Client | coord: 30, 
                      requestQueue: < 300 : Txn | operations: write(1,"c"),
                                                  readSet: empty, writeSet: empty,
                                                  version: eptVersion, consLv: one >,
                      waitingList: emptyTxnList, lockedKeys: empty,
                      executing: null, committed: null >
)
	   < 10 : Server | localRing: (([0],10),([4],20),([8],30),([12],40)), 
                       respFromRepl: empty, reqConsLv: empty,
                       datastore: empty > 
	   < 20 : Server | localRing: (([0],10),([4],20),([8],30),([12],40)), 
                       respFromRepl: empty, reqConsLv: empty,
                       datastore: [1,"a",0.0] > 
	   < 30 : Server | localRing: (([0],10),([4],20),([8],30),([12],40)), 
                       respFromRepl: empty, reqConsLv: empty,
                       datastore: [1,"a",0.0] > 
	   < 40 : Server | localRing: (([0],10),([4],20),([8],30),([12],40)), 
                       respFromRepl: empty, reqConsLv: empty,
                       datastore: [1,"a",0.0] > .
)

endm

set clear rules off .

rew initConfig .

